schema_version: 1

context:
  version: "0.19.0"

package:
  name: zapros
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/z/zapros/zapros-${{ version }}.tar.gz
  sha256: 86de3bb7f785785587f1efaa114f6b7a1f99d5b8d27302acd68a9f1918f1ea16

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - h11 >=0.16.0
    - pywhatwgurl >=0.1.0
    - typing_extensions >=4.15.0

tests:
  - python:
      imports:
        - zapros
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Modern and extensible HTTP client for Python.
  license: MIT
  license_file: LICENSE
  homepage: https://zapros.dev
  documentation: https://zapros.dev

extra:
  recipe-maintainers:
    - synapticarbors
